version: '3'

services:
  db:
    image: postgres
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  front:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    command: npm start
    volumes:
      - .:/code
    ports:
      - "3000:3000"
    depends_on:
      - web
