# Generated by Django 2.1 on 2018-08-21 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='dishes_count',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
